### ISSUE TITLE
Errors upon property change or adding new node.

### ISSUE THREAD

**Issue by FredRus** [vkter/Sverchok-Bmesh#3]
Every time I use the Bmesh module, the moment I change any property of node linked to the node system, it raises error _ReferenceError('BMesh data of type BMesh has been removed')_. This is an annoying bug that I look forward to getting fixed. I'm using all the processing in a node group as you recommended but the error still loads. Not until I use the stethoscope at the beginning of the node system, the error won't go away. It slows down the process and this is not intuitive.

**Comment by vkter** [comment]
Here I will make some explanations for your question:
The objects processed by bmesh should be deleted at last, so I turned on deletion by default, and later I will change it to off by default
![image](https://user-images.githubusercontent.com/74725748/211987174-bd7512e9-4998-4a0b-a38c-d42b7bc73fe6.png)

**Comment by FredRus** [comment]
This is what happens when I don't free the bmesh:
![Bmesh_free()](https://user-images.githubusercontent.com/120553860/212069639-3a6d9f3f-d04d-4476-a8b1-2b4e0962971a.png)

**Comment by vkter** [comment]
The BMESH processing is a bit special, because we always deal with objects in the same memory. When the same object is repeatedly executed, the same command will occur. I will give a few solutions below:
1. Use global update to update all nodes
2. Make sure to clear the container before filling the cube
![image](https://user-images.githubusercontent.com/74725748/212078540-14fa9be8-a11a-437d-80c3-11aafb1d012d.png)
3. Use the script node output container object and input connection with the group. This will generate a new container each time it is updated
![image](https://user-images.githubusercontent.com/74725748/212081063-2c477baa-8f46-48f9-812a-bbfee9ff4fd7.png)

**Comment by FredRus** [comment]
Works but leaves behind unnecessary meshes in Blender. Which means if any of the values have been changed, one more mesh is made. Just dragging different sliders a bit resulted in having 85 unused meshes.

**Comment by vkter** [comment]
You should try to use the BMESH node in the group as much as possible. I did not happen in the example.

**Comment by vkter** [comment]
![dd](https://user-images.githubusercontent.com/74725748/212214396-8f150e93-2797-42fa-9ea4-0e137a84e3be.gif)

**Comment by vkter** [comment]
Thank you for your feedback, I just fixed this problem, now it will not generate additional Mesh
![image](https://user-images.githubusercontent.com/74725748/212241683-96522a29-9714-4e23-a5e6-b0d596db2254.png)
