### ISSUE TITLE
BMesh Ops Node

### ISSUE THREAD

**Issue by FredRus** [vkter/Sverchok-Bmesh#4]
# Proposal
The BMesh Ops Node is huge and needs more customization for a better user experience. I have an
experimental lite version of the idea and I look forward to hearing from you.

## Features

- Edit _Bmesh_ Geometry more conveniently
- No need for group nodes
- Auto _free Bmesh_
- Pass in indices or masks for operations
- Socket type detections and defaults
- Quick links necessary inputs
- Dynamic sockets
-  Very unlike Bmesh removal Errors

## Showcase:
![basic_bmesh_lite](https://user-images.githubusercontent.com/120553860/222807410-ebfadf3e-7273-4c5a-9c44-55c6865b27bf.png)

**Comment by vkter** [comment]
This is a great change. At first, due to the huge nature of BMESH, I ignored the convenience of node control. I also hope that users will use them in the script environment. Now, your idea will change this situation.
These changes will be complicated. 
As an open source project, you can create a branch to contribute to the project
Or are you willing to be a project partner of the project so that you will be able to update them quickly

**Comment by FredRus** [comment]
You're right, it can get really complicated. The processing sometimes confuses me. It leaves behind huge room for improvement. I'll make A Bmesh Lite branch and see what you think.

**Comment by vkter** [comment]
Usually we use VSCode, here are detailed introductions:
https://code.visualstudio.com/docs/sourcecontrol/github

**Comment by FredRus** [comment]
So, should I basically make a pull request?

**Comment by vkter** [comment]
Probably this step:
1. Create an own branch (in the pull requests)
2. Use VSCODE to clone your own branch locally
3 When the project is completed, they can be submitted to the trunk

**Comment by FredRus** [comment]
Well, the unfortunate part is that I can't access VSCODE right now because I have no admin rights on the computer I'm using.

**Comment by vkter** [comment]
Then, you can visit on the webpage for the time being
I will continue to provide help to promote this change
